# This environment is needed to build Leafcutter conda package with boa
name: boabuild
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - boa=0.14
  - anaconda
  - mamba
