name: build-conda-leafcutter
on:
  push:
    branches:
      - workflows

jobs:
  bouild-upload-leafcutter:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: create environment with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          channels: conda-forge,defaults
          channel-priority: true
          auto-activate-base: true
          activate-environment: true
          mamba-version: "*"

      - name: build r-leafcutter conda package
        shell: bash -el {0}
        run: |
          mamba create -n boabuild python=3.10
          mamba activate boabuild
          mamba install -y boa -c conda-forge
          conda mambabuild conda_recipe

      - name: push buid to anaconda
        shell: bash -el {0}
        run: |
          mamba install -y anaconda -c anaconda
          export ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
          anaconda upload --label ${{ github.ref_name }} /usr/share/miniconda/envs/boabuild/conda-bld/linux-64/*.tar.bz2
