name: build-conda-leafcutter
on:
  push:
    branches:
      - workflows

jobs:
  create-env:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
        working-directory: conda_recipe

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: create environment with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          auto-activate-base: false
          activate-environment: base
          environment-file: .github/envs/conda-build-env.yml

      - name: check solution
        run: |
          mamba list
          pwd
