name: build-conda-leafcutter
on:
  push:
    branches:
      - workflows

jobs:
  bouild-upload-leafcutter:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: create environment with mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          cache-env: true

      - name: build r-leafcutter conda package
        working-directory: conda-recipe
        run: |
          mamba create -n boabuild python=3.10
          mamba activate boabuild
          mamba install boa
          conda mambabuild .
          mamba install anaconda
          export ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
          anaconda upload --label ${{ github.ref_name }} /usr/share/miniconda/envs/boabuild/conda-bld/linux-64/*.tar.bz2
