name: build-conda-leafcutter
on:
  push:
    branches:
      - workflows

jobs:
  bouild-upload-leafcutter:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
        working-directory: conda_recipe

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: create environment with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          auto-activate-base: false
          activate-environment: boabuild
          environment-file: .github/envs/conda-build-env.yml

      - name: build r-leafcutter conda package
        run: |
          mamba env list
          anaconda
          export ANACONDA_API_TOKEN=${{ secrets.ANAKONDA_TOKEN }}
          # conda mambabuild .
          anaconda upload --label ${{ github.ref_name }} /usr/share/miniconda/envs/boabuild/conda-bld/linux-64/*.tar.bz2
