name: build-conda-leafcutter
on:
  push:
    branches:
      - workflows

jobs:
  bouild-upload-leafcutter:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
        working-directory: conda_recipe

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: create environment with mamba
        uses: mamba-org/provision-with-micromamba@main

        with:
          channels: conda-forge,bioconda,defaults
          environment-file: .github/envs/conda-build-env.yml
          cache-downloads: true
          cache-env: true

      - name: build r-leafcutter conda package
        run: |
          micromamba env list
          export ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
          conda mambabuild
          anaconda upload --label ${{ github.ref_name }} /usr/share/miniconda/envs/boabuild/conda-bld/linux-64/*.tar.bz2
